apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-naumann-cloud-tls
spec:
  secretName: k8s-naumann-cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.naumann.cloud
  dnsNames:
    - k8s.naumann.cloud
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.naumann.cloud